version: '3.4'

services: 

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: DockerfileStore
    environment: 
      - ProductEndpoint=http://backend:8080
      - ImagePrefix=http://localhost:32001/images
      - ConnectionStrings:AppConfig=Endpoint=https://mustafaconfig.azconfig.io;Id=2vRh;Secret=HJO9EDsGQvVafy23waqluLOSbIlOCcb3VvES8dQu2P4=
    ports:
      - "32000:8080"
    depends_on: 
      - backend
  backend:
    image: productservice
    build: 
      context: .
      dockerfile: DockerfileProducts
    ports: 
      - "32001:8080"
